name: SmartAgri-CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Python deps
        run: pip install paho-mqtt pytest
      - name: Run tests
        run: pytest
